# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(array_2d)

# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:")
print(array_3d)

1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
# Print the shape of the array
print("Shape:", array_1d.shape)

# Print the number of dimensions
print("Number of dimensions:", array_1d.ndim)

# Print the data type of the array
print("Data type:", array_1d.dtype)

# Print the size (number of elements) of the array
print("Size:", array_1d.size)

# Print the type
print("Type:", type(array_1d))

Shape: (5,)
Number of dimensions: 1
Data type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array

# Print the shape of the array
print("Shape:", array_2d.shape)

# Print the number of dimensions
print("Number of dimensions:", array_2d.ndim)

# Print the data type of the array
print("Data type:", array_2d.dtype)

# Print the size (number of elements) of the array
print("Size:", array_2d.size)

# Print the type
print("Type:", type(array_2d))

Shape: (3, 3)
Number of dimensions: 2
Data type: int64
Size: 9
Type: <class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array

# Print the shape of the array
print("Shape:", array_3d.shape)

# Print the number of dimensions
print("Number of dimensions:", array_3d.ndim)

# Print the data type of the array
print("Data type:", array_3d.dtype)

# Print the size (number of elements) of the array
print("Size:", array_3d.size)

# Print the type
print("Type:", type(array_3d))

Shape: (2, 2, 3)
Number of dimensions: 3
Data type: int64
Size: 12
Type: <class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(array_1d, columns=['Column1'])

print(df)

   Column1
0        1
1        2
2        3
3        4
4        5


In [7]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2, 3))
print(zeros_array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [10]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0, 100, 3)
print(array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
print(random_array)

[[7 0]
 [4 8]
 [7 5]
 [4 6]
 [4 5]
 [4 5]
 [1 5]]


In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3, 5)
print(random_float_array)

[[0.53795647 0.28449291 0.66278936 0.34280423 0.84702883]
 [0.55439748 0.21392937 0.30362377 0.34210313 0.99316998]
 [0.89731391 0.86244001 0.55742541 0.85664412 0.45130176]]


In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0, 10, size=(4, 6))
print(random_array)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(42)
random_array = np.random.randint(1, 11, size=(3, 7))

print("Array:")
print(random_array)

# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_array)
print("\nUnique numbers:")
print(unique_numbers)

Array:
[[ 7  4  8  5  7 10  3]
 [ 7  8  5  4  8  8  3]
 [ 6  5  2  8  6  2  5]]

Unique numbers:
[ 2  3  4  5  6  7  8 10]


In [16]:
# Find the 0'th index of the latest array you created
zeroth_index = random_array[0]

print("\n0'th index:")
print(zeroth_index)


0'th index:
[ 7  4  8  5  7 10  3]


In [17]:
# Get the first 2 rows of latest array you created
first_two_rows = random_array[:2]
print("\nFirst two rows:")
print(first_two_rows)


First two rows:
[[ 7  4  8  5  7 10  3]
 [ 7  8  5  4  8  8  3]]


In [18]:
# Get the first 2 values of the first 2 rows of the latest array
first_two_values_of_first_two_rows = random_array[:2, :2]

print("\nFirst two values of the first two rows:")
print(first_two_values_of_first_two_rows)


First two values of the first two rows:
[[7 4]
 [7 8]]


In [19]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

np.random.seed(42)

# Create a random array of integers between 0 and 10 with size (3, 5)
random_array = np.random.randint(0, 11, size=(3, 5))
                                 
ones_array = np.ones((3, 5))

print("Random array:")
print(random_array)

print("\nOnes array:")
print(ones_array)

Random array:
[[ 6  3 10  7  4]
 [ 6  9  2  6 10]
 [10  7  4  3  7]]

Ones array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# Add the two arrays together
added_arrays = random_array + ones_array
print(added_arrays)

[[ 7.  4. 11.  8.  5.]
 [ 7. 10.  3.  7. 11.]
 [11.  8.  5.  4.  8.]]


In [21]:
# Create another array of ones of shape (5, 3)
ones_array_2 = np.ones((5, 3))
print(ones_array_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# Try add the array of ones and the other most recent array together
try:
    added_arrays = random_array + ones_array_2
    print(added_arrays)
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (3,5) (5,3) 


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [25]:
# Create another array of ones of shape (3, 5)
ones_array_3 = np.ones((3, 5))
print(ones_array_3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
# Subtract the new array of ones from the other most recent array
subtracted_arrays = random_array - ones_array_3
print(subtracted_arrays)


[[5. 2. 9. 6. 3.]
 [5. 8. 1. 5. 9.]
 [9. 6. 3. 2. 6.]]


In [28]:
# Multiply the ones array with the latest array
multiplied_arrays = random_array * ones_array_3
print(multiplied_arrays)

[[ 6.  3. 10.  7.  4.]
 [ 6.  9.  2.  6. 10.]
 [10.  7.  4.  3.  7.]]


In [29]:
# Take the latest array to the power of 2 using '**'
power_of_2_array = random_array ** 2
print(power_of_2_array)

[[ 36   9 100  49  16]
 [ 36  81   4  36 100]
 [100  49  16   9  49]]


In [30]:
# Do the same thing with np.square()
squared_array = np.square(random_array)
print(squared_array)

[[ 36   9 100  49  16]
 [ 36  81   4  36 100]
 [100  49  16   9  49]]


In [32]:
# Find the mean of the latest array using np.mean()
array_mean = np.mean(random_array)
print(array_mean)

6.266666666666667


In [33]:
# Find the maximum of the latest array using np.max()
max_arr = np.max(random_array)
print(max_arr)

10


In [34]:
# Find the minimum of the latest array using np.min()
min_arr = np.min(random_array)
print(min_arr)

2


In [35]:
# Find the standard deviation of the latest array
arr_std = np.std(random_array)
print(arr_std)

2.594010194445829


In [36]:
# Find the variance of the latest array
arr_var = np.var(random_array)
print(arr_var)

6.728888888888889


In [37]:
# Reshape the latest array to (3, 5, 1)
reshaped_arr = random_array.reshape((3, 5, 1))
print(reshaped_arr)

[[[ 6]
  [ 3]
  [10]
  [ 7]
  [ 4]]

 [[ 6]
  [ 9]
  [ 2]
  [ 6]
  [10]]

 [[10]
  [ 7]
  [ 4]
  [ 3]
  [ 7]]]


In [38]:
# Transpose the latest array
transposed_arr = random_array.T
print(transposed_arr)

[[ 6  6 10]
 [ 3  9  7]
 [10  2  4]
 [ 7  6  3]
 [ 4 10  7]]


What does the transpose do?

In [39]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_1 = np.random.randint(0, 11, size=(3, 3))

random_array_2 = np.random.randint(0, 11, size=(3, 2))

print(random_array_1)
print(random_array_2)

[[7 2 5]
 [4 1 7]
 [5 1 4]]
[[ 0  9]
 [ 5  8]
 [ 0 10]]


In [41]:
# Perform a dot product on the two newest arrays you created
dot_prod = random_array_1 @ random_array_2
print(dot_prod)

[[ 10 129]
 [  5 114]
 [  5  93]]


In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(42)

random_arr1 = np.random.randint(0, 11, size=(4, 3))
random_arr2 = np.random.randint(0, 11, size=(4, 3))

print(random_arr1)
print(random_arr2)

[[ 6  3 10]
 [ 7  4  6]
 [ 9  2  6]
 [10 10  7]]
[[4 3 7]
 [7 2 5]
 [4 1 7]
 [5 1 4]]


In [44]:
# Perform a dot product on the two newest arrays you created
dot_product = random_arr1 @ random_arr2.T
print(dot_product)

[[103  98  97  73]
 [ 82  87  74  63]
 [ 84  97  80  71]
 [119 125  99  88]]


It doesn't work. How would you fix it?

In [45]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_product = random_arr1 @ random_arr2.T
print(dot_product)

[[103  98  97  73]
 [ 82  87  74  63]
 [ 84  97  80  71]
 [119 125  99  88]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [46]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

# Create a random array of integers between 0 and 10 with size (3, 3)
random_array_1 = np.random.randint(0, 11, size=(3, 3))

# Create another random array of integers between 0 and 10 with size (3, 3)
random_array_2 = np.random.randint(0, 11, size=(3, 3))

# Print the arrays
print("Random array 1:")
print(random_array_1)

print("\nRandom array 2:")
print(random_array_2)

Random array 1:
[[ 0  9  5]
 [ 8  0 10]
 [10  9  2]]

Random array 2:
[[6 3 8]
 [2 4 2]
 [6 4 8]]


In [47]:
# Compare the two arrays with '>'
comparison = random_array_1 > random_array_2
print(comparison)

[[False  True False]
 [ True False  True]
 [ True  True False]]


What happens when you compare the arrays with `>`?

In [48]:
# Compare the two arrays with '>='
comparison = random_array_1 >= random_array_2
print(comparison)

[[False  True False]
 [ True False  True]
 [ True  True False]]


In [52]:
# Find which elements of the first array are greater than 7
greater_than_seven = random_array_1 > 7
print(greater_than_seven)

values_greater_than_seven = random_array_1[greater_than_seven]
print(values_greater_than_seven)

[[False  True False]
 [ True False  True]
 [ True  True False]]
[ 9  8 10 10  9]


In [53]:
# Which parts of each array are equal? (try using '==')
equal_elems = random_array_1 == random_array_2
print(equal_elems)

[[False False False]
 [False False False]
 [False False False]]


In [54]:
# Sort one of the arrays you just created in ascending order
sorted_array_1 = np.random.randint(0, 11, size=(3, 3))

# Sort the array
sorted_array_1 = np.sort(random_array_1)

print("Sorted array:")
print(sorted_array_1)

Sorted array:
[[ 0  5  9]
 [ 0  8 10]
 [ 2  9 10]]


In [56]:
# Sort the indexes of one of the arrays you just created
sorted_indices = np.argsort(random_array_1)
print(sorted_indices)

[[0 2 1]
 [1 0 2]
 [2 1 0]]


In [59]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(random_array_1)
print("Index of the max value:", max_index)

Index of the max value: 5


In [61]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(random_array_1)
print("Index of the min value:", min_index)

Index of the min value: 0


In [63]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indices = np.argmax(random_array_1, axis=1)
print("Indices of the max values along each row:", max_indices)

Indices of the max values along each row: [1 2 0]


In [64]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices = np.argmin(random_array_1, axis=0)
print("Indices of the min values across the 0th axis", min_indices)

Indices of the min values across the 0th axis [0 1 2]


In [65]:
# Create an array of normally distributed random numbers
normal_arr = np.random.normal(loc=0, scale=1, size=(3, 3))
print(normal_arr)

[[-0.74907652 -0.77838201  0.94884286]
 [ 1.58085059 -0.36817094  0.37556463]
 [-1.19315823 -0.4090519  -0.44674147]]


In [67]:
# Create an array with 10 evenly spaced numbers between 1 and 100
linspace_arr = np.linspace(1, 100, 10)

print(linspace_arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.