In [226]:
import numpy as np

## DataTypes & Attributes

In [227]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [228]:
 type(a1)

numpy.ndarray

In [229]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [230]:
 a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [231]:
a3

In [232]:
a1.shape

In [233]:
a2.shape

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a1

array([1, 2, 3])

In [236]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [237]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [238]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [239]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [240]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [241]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [242]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [243]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [244]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating arrays

In [245]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [246]:
sample_array.dtype

dtype('int64')

In [247]:
ones = np.ones((2, 3))

In [248]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [249]:
ones.dtype

dtype('float64')

In [250]:
type(ones)

numpy.ndarray

In [251]:
zeros = np.zeros((2, 3))

In [252]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [253]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [254]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [255]:
random_array.size

15

In [256]:
random_array.shape

(3, 5)

In [257]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256]])

In [258]:
random_array_2.shape

(5, 3)

In [259]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384],
       [0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514]])

In [260]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [261]:
# Pseudo-random numbers
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [262]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [263]:
random_array_4.shape

(5, 3)

# Viewing arrays and matrices

In [264]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [265]:
a1

array([1, 2, 3])

In [266]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [267]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [268]:
a1[0]

1

In [269]:
a2.shape

(2, 3)

In [270]:
a2[0]

array([1. , 2. , 3.3])

In [271]:
a3.shape

(2, 3, 3)

In [272]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [273]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [274]:
a2[1]

array([4. , 5. , 6.5])

In [275]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [276]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [277]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [278]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [279]:
# Get the first 4 nums of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

# 4. Manipulating & comparing arrays

### Arithmetic

In [280]:
a1

array([1, 2, 3])

In [281]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [282]:
a1 + ones

array([2., 3., 4.])

In [283]:
a1 - ones

array([0., 1., 2.])

In [284]:
a1 * ones


array([1., 2., 3.])

In [285]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [286]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [287]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [288]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
a1 + ones

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a1 / 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

### Use Python's methods `(sum()` on Python datatypes and use NumPy's methods on NumPy arrays `(np.sum()`.

In [ ]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

In [ ]:
17900 / 34

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of nums is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each num is diff to the mean
    # Higher variance = wider range of nums
    # Lower variance = lower rage of nums

np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of Std & Var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

# Reshaping & Transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
# Transpose = switches the axis'
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

# Dot Product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# http://matrixmultiplication.xyz/

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

# Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                           index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'],
                           columns=['Almond butter', 'Peanut butter', 'Cashew Butter'])
weekly_sales

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

In [ ]:
prices.shape

In [ ]:
# create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=['Price'],
                            columns=['Almond butter', 'Peanut butter', 'Cashew Butter'])
butter_prices

In [ ]:
prices

In [ ]:
prices.shape

In [ ]:
sales_amounts

In [ ]:
# Shapes aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
# Create daily sales
butter_prices

In [ ]:
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales

In [ ]:
weekly_sales.T.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

In [ ]:
weekly_sales.shape

In [ ]:
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

# Comparison Operators

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1 == a1

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 == a2

# Sorting Arrays

In [ ]:
random_array

In [ ]:
random_array.shape

In [ ]:
random_array = np.random.randint(10, size=(3, 5))

In [ ]:
random_array.shape

In [ ]:
random_array

In [ ]:
np.sort(random_array)

In [ ]:
random_array

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
np.argmax(a1)

In [ ]:
random_array

In [ ]:
np.argmax(random_array, axis=0)

In [ ]:
np.argmax(random_array, axis=1)

# Practical Example - NumPy in action!

In [ ]:
<img src="images/panda.png"/>

In [ ]:
# Turn an image into a NumPy Array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

In [ ]:
panda.size, panda.shape, panda.ndim

In [ ]:
panda[:5]

In [289]:
<img src="images/car-photo.png"/>

SyntaxError: invalid syntax (4202550140.py, line 1)

In [290]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [292]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

In [294]:
dog = imread("images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [295]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)